package cat.xojan.fittracker.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATIONS".
 */
public class Track {

    private Long id;
    private Double longitude;
    private Double lattitude;
    private java.util.Date date;
    private long workoutId;

    public Track() {
    }

    public Track(Long id) {
        this.id = id;
    }

    public Track(Long id, Double longitude, Double lattitude, java.util.Date date, long workoutId) {
        this.id = id;
        this.longitude = longitude;
        this.lattitude = lattitude;
        this.date = date;
        this.workoutId = workoutId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLattitude() {
        return lattitude;
    }

    public void setLattitude(Double lattitude) {
        this.lattitude = lattitude;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public long getWorkoutId() {
        return workoutId;
    }

    public void setWorkoutId(long workoutId) {
        this.workoutId = workoutId;
    }

}
