package cat.xojan.fittracker.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORKOUT".
 */
public class Workout {

    private Long id;
    private String title;
    private Long workoutTime;
    private Long startTime;
    private Long endTime;
    private Long distance;
    private String type;
    private String locations;

    public Workout() {
    }

    public Workout(Long id) {
        this.id = id;
    }

    public Workout(Long id, String title, Long workoutTime, Long startTime, Long endTime,
                   Long distance, String type, String locations) {
        this.id = id;
        this.title = title;
        this.workoutTime = workoutTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.distance = distance;
        this.type = type;
        this.locations = locations;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getWorkoutTime() {
        return workoutTime;
    }

    public void setWorkoutTime(Long workoutTime) {
        this.workoutTime = workoutTime;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Long getDistance() {
        return distance;
    }

    public void setDistance(Long distance) {
        this.distance = distance;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLocations() {
        return locations;
    }

    public void setLocations(String locations) {
        this.locations = locations;
    }
}
