package cat.xojan.fittracker.data.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cat.xojan.fittracker.data.entity.Workout;
import cat.xojan.fittracker.data.entity.Track;

import cat.xojan.fittracker.data.db.dao.WorkoutDao;
import cat.xojan.fittracker.data.db.dao.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workoutDaoConfig;
    private final DaoConfig trackDaoConfig;

    private final WorkoutDao workoutDao;
    private final TrackDao trackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workoutDaoConfig = daoConfigMap.get(WorkoutDao.class).clone();
        workoutDaoConfig.initIdentityScope(type);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        workoutDao = new WorkoutDao(workoutDaoConfig, this);
        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(Workout.class, workoutDao);
        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        workoutDaoConfig.getIdentityScope().clear();
        trackDaoConfig.getIdentityScope().clear();
    }

    public WorkoutDao getWorkoutDao() {
        return workoutDao;
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
